/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    pages: Page
    categories: Category
    posts: Post
    tags: Tag
    users: User
    media: Media
    forms: Form
    'form-submissions': FormSubmission
  }
  globals: {
    company: Company
    'main-menu': MainMenu
  }
}
export interface Page {
  id: string
  title: string
  layout: (
    | HeroBlock
    | HeaderSectionBlock
    | BlogSectionBlock
    | DividerBlock
    | FormBlock
  )[]
  slug?: string
  updatedAt: string
  createdAt: string
  _status?: 'draft' | 'published'
}
export interface HeroBlock {
  featuredPost?: string | Post
  title?: string
  description?: string
  image?: string | Media
  primaryAction: {
    type?: 'reference' | 'custom'
    reference: {
      value: string | Page
      relationTo: 'pages'
    }
    url: string
    label: string
  }
  secondaryAction: {
    type?: 'reference' | 'custom'
    reference: {
      value: string | Page
      relationTo: 'pages'
    }
    url: string
    label: string
  }
  id?: string
  blockName?: string
  blockType: 'hero'
}
export interface Post {
  id: string
  slug?: string
  title?: string
  author?: string | User
  publishedDate?: string
  image?: string | Media
  category?: string | Category
  tags?: string[] | Tag[]
  content?: {
    [k: string]: unknown
  }[]
  updatedAt: string
  createdAt: string
  _status?: 'draft' | 'published'
}
export interface User {
  id: string
  name: string
  slug?: string
  avatar?: string | Media
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string
  resetPasswordExpiration?: string
  salt?: string
  hash?: string
  loginAttempts?: number
  lockUntil?: string
  password?: string
}
export interface Media {
  id: string
  alt: string
  updatedAt: string
  createdAt: string
  url?: string
  filename?: string
  mimeType?: string
  filesize?: number
  width?: number
  height?: number
  sizes?: {
    card?: {
      url?: string
      width?: number
      height?: number
      mimeType?: string
      filesize?: number
      filename?: string
    }
    feature?: {
      url?: string
      width?: number
      height?: number
      mimeType?: string
      filesize?: number
      filename?: string
    }
  }
}
export interface Category {
  id: string
  name?: string
}
export interface Tag {
  id: string
  slug?: string
  name?: string
}
export interface HeaderSectionBlock {
  title?: string
  description?: string
  id?: string
  blockName?: string
  blockType: 'headerSection'
}
export interface BlogSectionBlock {
  show?: '3' | '6' | '9'
  id?: string
  blockName?: string
  blockType: 'blogSection'
}
export interface DividerBlock {
  id?: string
  blockName?: string
  blockType: 'divider'
}
export interface FormBlock {
  form: string | Form
  enableIntro?: boolean
  introContent: {
    [k: string]: unknown
  }[]
  id?: string
  blockName?: string
  blockType: 'formBlock'
}
export interface Form {
  id: string
  title: string
  fields?: (
    | {
        name: string
        label?: string
        width?: number
        defaultValue?: string
        required?: boolean
        id?: string
        blockName?: string
        blockType: 'text'
      }
    | {
        name: string
        label?: string
        width?: number
        defaultValue?: string
        required?: boolean
        id?: string
        blockName?: string
        blockType: 'textarea'
      }
    | {
        name: string
        label?: string
        width?: number
        defaultValue?: string
        options?: {
          label: string
          value: string
          id?: string
        }[]
        required?: boolean
        id?: string
        blockName?: string
        blockType: 'select'
      }
    | {
        name: string
        label?: string
        width?: number
        required?: boolean
        id?: string
        blockName?: string
        blockType: 'email'
      }
    | {
        name: string
        label?: string
        width?: number
        required?: boolean
        id?: string
        blockName?: string
        blockType: 'state'
      }
    | {
        name: string
        label?: string
        width?: number
        required?: boolean
        id?: string
        blockName?: string
        blockType: 'country'
      }
    | {
        name: string
        label?: string
        width?: number
        defaultValue?: number
        required?: boolean
        id?: string
        blockName?: string
        blockType: 'number'
      }
    | {
        name: string
        label?: string
        width?: number
        required?: boolean
        defaultValue?: boolean
        id?: string
        blockName?: string
        blockType: 'checkbox'
      }
    | {
        message?: {
          [k: string]: unknown
        }[]
        id?: string
        blockName?: string
        blockType: 'message'
      }
  )[]
  submitButtonLabel?: string
  confirmationType?: 'message' | 'redirect'
  confirmationMessage: {
    [k: string]: unknown
  }[]
  redirect?: {
    url: string
  }
  emails?: {
    emailTo?: string
    cc?: string
    bcc?: string
    replyTo?: string
    emailFrom?: string
    subject: string
    message?: {
      [k: string]: unknown
    }[]
    id?: string
  }[]
  updatedAt: string
  createdAt: string
}
export interface FormSubmission {
  id: string
  form: string | Form
  submissionData?: {
    field: string
    value: string
    id?: string
  }[]
  updatedAt: string
  createdAt: string
}
export interface Company {
  id: string
  name?: string
  logo?: string | Media
  updatedAt?: string
  createdAt?: string
}
export interface MainMenu {
  id: string
  navItems?: {
    link: {
      type?: 'reference' | 'custom'
      reference: {
        value: string | Page
        relationTo: 'pages'
      }
      url: string
      label: string
    }
    id?: string
  }[]
  updatedAt?: string
  createdAt?: string
}
